name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  # schedule:
  #   - cron: '11 1 * * 1'
  push:
    branches: [ kowis-build ]
#  pull_request:
    branches: [ kowis-build ]
  workflow_dispatch:

jobs:
  build:

    environment: ${{ matrix.environment }}
    runs-on: self-hosted
    permissions:
      contents: read
#     packages: write

    strategy:
      matrix:
        include:
#         - registry: ghcr.io
#           environment: 'GitHub'
          - registry: registry.light.kow.is
            context: authoritative
            image: powerdns-server
            environment: 'Registry.light.kow.is'
          - registry: registry.light.kow.is
            context: dnsdist
            image: dnsdist
            environment: 'Registry.light.kow.is'
          - registry: registry.light.kow.is
            context: recursor
            image: powerdns-recursor
            environment: 'Registry.light.kow.is'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry docker.io
        if: ${{ 'docker.io' == matrix.registry && github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          registry: ${{ matrix.registry }}
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Log into registry ghcr.io
        if: ${{ 'ghcr.io' == matrix.registry && github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          registry: ${{ matrix.registry }}
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Log into registry registry.light.kow.is
        if: ${{ 'registry.light.kow.is' == matrix.registry && github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          registry: ${{ matrix.registry }}
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ matrix.registry }}/library/${{ matrix.image }}
          flavor: |
            latest=false
          tags: |
            type=raw,value=latest

# don't need this when the arch is arm64 already, maybe there's a way to make it check?
#      - name: Set up QEMU for buildx
#        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}/.
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
